
services:
  - type: web
    name: discord-bot-french
    env: python
    buildCommand: pip install -r render_requirements.txt
    startCommand: python main.py
    plan: free
    envVars:
      - key: DISCORD_TOKEN
        sync: false
      - key: PORT
        value: "10000"
    autoDeploy: false
    healthCheckPath: /health
